INFO:smsapp.views:2024-11-15: User varun1@gmail.com logged in successfully.
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: rahul.yadav@bhaaratwealthgroup.com, campaign title: dayone
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 5
INFO:smsapp.functions.send_messages:Coins deducted: 5. Remaining balance: 9967
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: dayone, user: rahul.yadav@bhaaratwealthgroup.com
INFO:smsapp.views:2024-11-15: User rahul.yadav@bhaaratwealthgroup.com logged in successfully.
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: rahul.yadav@bhaaratwealthgroup.com, campaign title: dayone
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 5
INFO:smsapp.functions.send_messages:Coins deducted: 5. Remaining balance: 9962
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: dayone, user: rahul.yadav@bhaaratwealthgroup.com
INFO:smsapp.views:2024-11-15: User rahul.yadav@bhaaratwealthgroup.com logged in successfully.
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: rahul.yadav@bhaaratwealthgroup.com, campaign title: report_one
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 0
INFO:smsapp.functions.send_messages:Coins deducted: 0. Remaining balance: 9962
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: report_one, user: rahul.yadav@bhaaratwealthgroup.com
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: rahul.yadav@bhaaratwealthgroup.com, campaign title: report_one
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 5
INFO:smsapp.functions.send_messages:Coins deducted: 5. Remaining balance: 9957
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: report_one, user: rahul.yadav@bhaaratwealthgroup.com
INFO:smsapp.views:2024-11-15: User rahul.yadav@bhaaratwealthgroup.com logged in successfully.
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: rahul.yadav@bhaaratwealthgroup.com, campaign title: abcd
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 4
INFO:smsapp.functions.send_messages:Coins deducted: 4. Remaining balance: 9953
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: abcd, user: rahul.yadav@bhaaratwealthgroup.com
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: rahul.yadav@bhaaratwealthgroup.com, campaign title: dayone
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 2
INFO:smsapp.functions.send_messages:Coins deducted: 2. Remaining balance: 9951
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: dayone, user: rahul.yadav@bhaaratwealthgroup.com
INFO:smsapp.views:2024-11-15: User opinder@gmail.com logged in successfully.
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: rahul.yadav@bhaaratwealthgroup.com, campaign title: dayone
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 1
INFO:smsapp.functions.send_messages:Coins deducted: 1. Remaining balance: 9950
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: dayone, user: rahul.yadav@bhaaratwealthgroup.com
INFO:smsapp.views:2024-11-15: User opinder@gmail.com logged in successfully.
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: opinder@gmail.com, campaign title: 1st
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 1
INFO:smsapp.functions.send_messages:Coins deducted: 1. Remaining balance: 1639
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: 1st, user: opinder@gmail.com
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: rahul.yadav@bhaaratwealthgroup.com, campaign title: dayone
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 2
INFO:smsapp.functions.send_messages:Coins deducted: 2. Remaining balance: 9948
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: dayone, user: rahul.yadav@bhaaratwealthgroup.com
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: rahul.yadav@bhaaratwealthgroup.com, campaign title: bwgdayone
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 6
INFO:smsapp.functions.send_messages:Coins deducted: 6. Remaining balance: 9942
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: bwgdayone, user: rahul.yadav@bhaaratwealthgroup.com
INFO:root:Error: cannot access local variable 'user_response' where it is not associated with a value
INFO:root:filter_message_response None
INFO:root:Error: cannot access local variable 'user_response' where it is not associated with a value
INFO:root:filter_message_response None
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: rahul.yadav@bhaaratwealthgroup.com, campaign title: bwgdayone
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 51
INFO:smsapp.functions.send_messages:Coins deducted: 51. Remaining balance: 9891
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: bwgdayone, user: rahul.yadav@bhaaratwealthgroup.com
INFO:root:Error: cannot access local variable 'user_response' where it is not associated with a value
INFO:root:filter_message_response None
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: rahul.yadav@bhaaratwealthgroup.com, campaign title: bwgdayone
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 2
INFO:smsapp.functions.send_messages:Coins deducted: 2. Remaining balance: 9889
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: bwgdayone, user: rahul.yadav@bhaaratwealthgroup.com
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:root:Sending flow messages for user: opinder@gmail.com, flow_name: single
INFO:root:Calculated money data for sending flow messages: 1
INFO:smsapp.functions.send_messages:Coins deducted: 1. Remaining balance: 1638
INFO:root:Messages sent successfully for campaign: single, user: opinder@gmail.com
INFO:smsapp.views:2024-11-15: User rahul.yadav@bhaaratwealthgroup.com logged in successfully.
INFO:root:user_response Hi
INFO:root:Error: cannot access local variable 'reply_text' where it is not associated with a value
INFO:root:Error: 'NoneType' object has no attribute 'message_type'
INFO:root:filter_message_response None
INFO:root:user_response Can you send details ?
INFO:root:Error: cannot access local variable 'reply_text' where it is not associated with a value
INFO:root:Error: 'NoneType' object has no attribute 'message_type'
INFO:root:filter_message_response None
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: rahul.yadav@bhaaratwealthgroup.com, campaign title: bwgdayone
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 4
INFO:smsapp.functions.send_messages:Coins deducted: 4. Remaining balance: 9885
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: bwgdayone, user: rahul.yadav@bhaaratwealthgroup.com
INFO:root:Error: cannot access local variable 'user_response' where it is not associated with a value
INFO:root:filter_message_response None
INFO:root:Error: cannot access local variable 'user_response' where it is not associated with a value
INFO:root:filter_message_response None
INFO:root:discount 98
INFO:root:discountnumber 124
INFO:smsapp.functions.send_messages:Sending messages for user: rahul.yadav@bhaaratwealthgroup.com, campaign title: dayone
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 127
INFO:smsapp.functions.send_messages:Coins deducted: 127. Remaining balance: 9758
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: dayone, user: rahul.yadav@bhaaratwealthgroup.com
INFO:root:Error: cannot access local variable 'user_response' where it is not associated with a value
INFO:root:filter_message_response None
INFO:root:Error: cannot access local variable 'user_response' where it is not associated with a value
INFO:root:filter_message_response None
[UID:1024][3741233] Child process with pid: 3836370 was killed by signal: 15, core dumped: no
[UID:1024][3741233] Child process with pid: 3838289 was killed by signal: 15, core dumped: no
IDs None None None
4::dmlkZW8vbXA0:ARa7avInUuPbAKqZP68qrhDmlwhc9P7zdvRET2xZAdGq462AsePzAon9RfbazZb4MaTScwpOnfW2WV6RvrWtX-B4i-re86wJx36y5ild7813VQ:e:1731995120:465471839698794:61565150340230:ARbipUhjGAznkKsGX3w
4::dmlkZW8vbXA0:ARZGO2Dcvzqbgo0cJo0fOBhGzmU_objIZLQNhkNoHeNon_aW4mHaVs3OrBOko66ILikLr47JtWzDh-UK5kVNh2vjInp9RARZiH-xxMHIDYfE_w:e:1731995120:465471839698794:61565150340230:ARZaKZL_gMrmiSSfrbQ
IDs None None None
4::dmlkZW8vbXA0:ARYOM9y0i0u5VBlwjfqlqPyPJO6OiHVTfQXkwJywExPi6ilRwS2TJ77Kk6-EE4LmZc-a1DKYqY2tk3irBay_eWo6Bn2bw1hA4E-X28dgA0ES5g:e:1731995667:465471839698794:61565150340230:ARYwCvjt21Lcafozc6E
4::dmlkZW8vbXA0:ARZ_AVrTSELkNwbavqS3MZeUz8462GJx-_lLTUvQb2EC09Nx_9Fq_VfABD511OJkyIcyksfAygnvE1TLMhbuuaFl4gtI04TsGNd6WkuC76_8rA:e:1731995667:465471839698794:61565150340230:ARa-UBlBboSUav2aM-o
IDs None None None
4::dmlkZW8vbXA0:ARabp_Zg61nkXigzHvlhu2JIxKuxT3dChmc5m0gzMCZAQdtoJoc42-s5ZnRhgZi0rxgtoyymhDTghHiPwuOzIVcY4gQTG7tEOxZo4EWbgEJwAQ:e:1731996063:465471839698794:61565150340230:ARZw2fePHBTxjm6UZ6A
4::dmlkZW8vbXA0:ARaiW4rD8m8t3Mim1cZknyc7Jlz35BXcQ2aQzBgmnvTL0PlgCQqI4rtrYfC8WzLqTAhkvo-FiVI9uXi-Ph-5W2vUHGeEZv-Fr6UO6ZjWclEAew:e:1731996063:465471839698794:61565150340230:ARb9kiCxnK78jcK1DK8
IDs None None None
Template 'utility' deleted successfully.
Template 'utility' deleted successfully.
Template 'bharathwelth' deleted successfully.
Template 'bharathwelth' deleted successfully.
IDs None None None
4::dmlkZW8vbXA0:ARay9UpXmTHBA16HK--QpxeJzZwMkp4VMjGD981Hxp858bgqL_jwU50aT6fvBjMFePnTQziiTxskaeT_jigyZtp8_tt0JSSdhoQODp3ohU8rew:e:1731996201:465471839698794:61565150340230:ARYy-joMw0oJLONftW4
4::dmlkZW8vbXA0:ARbWSnvUbCiUHtpTncpDrhU1Ep1hVnv1p7cwO8-BhzNPSO8gKvCQg2L7dol246dZzBxcxbTlAraQfTqx0LmcNUyol3IqtzgODuMqc_NYXwYPUg:e:1731996201:465471839698794:61565150340230:ARbh4W5nje1tB2RKyHo
Template 'abcdee' deleted successfully.
Template 'abcdee' deleted successfully.
Template 'dayn' deleted successfully.
Template 'dayn' deleted successfully.
Run time of job "schedule_messages (trigger: interval[0:45:00], next run at: 2024-11-15 11:48:28 IST)" was missed by 0:20:20.760347
INFO:smsapp.views:2024-11-15: User varun1@gmail.com logged in successfully.
INFO:smsapp.views:2024-11-15: User rahul.yadav@bhaaratwealthgroup.com logged in successfully.
INFO:smsapp.views:2024-11-15: User varun1@gmail.com logged in successfully.
INFO:root:discount 98
INFO:root:discountnumber 316
INFO:smsapp.functions.send_messages:Sending messages for user: rahul.yadav@bhaaratwealthgroup.com, campaign title: bwgdayone
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 323
INFO:smsapp.functions.send_messages:Coins deducted: 323. Remaining balance: 9435
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: bwgdayone, user: rahul.yadav@bhaaratwealthgroup.com
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: rahul.yadav@bhaaratwealthgroup.com, campaign title: bwgdayone
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 5
INFO:smsapp.functions.send_messages:Coins deducted: 5. Remaining balance: 9430
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: bwgdayone, user: rahul.yadav@bhaaratwealthgroup.com
INFO:root:Error: cannot access local variable 'user_response' where it is not associated with a value
INFO:root:filter_message_response None
INFO:root:user_response Imported me humse jada variety kabhi sochna bhi mat puri market me kahi milegi.
One stop destination for denim lovers\u2764\ufe0f
Killing machine
INFO:root:Error: cannot access local variable 'reply_text' where it is not associated with a value
INFO:root:Error: 'NoneType' object has no attribute 'message_type'
INFO:root:filter_message_response None
INFO:root:Error: cannot access local variable 'user_response' where it is not associated with a value
INFO:root:filter_message_response None
INFO:root:Error: cannot access local variable 'user_response' where it is not associated with a value
INFO:root:filter_message_response None
INFO:smsapp.views:User varun1@gmail.com logged in successfully.
INFO:smsapp.views:User varun1235 logged in successfully.
INFO:root:Final query: SELECT * FROM webhook_responses
INFO:root:Final parameters: []
INFO:root:Number of rows fetched: 70523
INFO:root:Sample messages in the data:
INFO:root:Sample messages: ['', '', '', '', None]
INFO:root:Sample timestamps: ['1723086598', '1723090671', '1723090893', '1723092429', '1723093143']
/home/fedqrbtb/wtsdealnow.com/whatsappsms/sms/smsapp/views.py:1391: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  counts = [int(df['message_body'].str.lower().str.contains(button.lower()).fillna(False).sum()) for button in button_names]
INFO:root:Final query: SELECT * FROM webhook_responses
INFO:root:Final parameters: []
INFO:root:Number of rows fetched: 70523
INFO:root:Sample messages in the data:
INFO:root:Sample messages: ['', '', '', '', None]
INFO:root:Sample timestamps: ['1723086598', '1723090671', '1723090893', '1723092429', '1723093143']
/home/fedqrbtb/wtsdealnow.com/whatsappsms/sms/smsapp/views.py:1391: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  counts = [int(df['message_body'].str.lower().str.contains(button.lower()).fillna(False).sum()) for button in button_names]
INFO:root:Final query: SELECT * FROM webhook_responses
INFO:root:Final parameters: []
INFO:root:Number of rows fetched: 70523
INFO:root:Sample messages in the data:
INFO:root:Sample messages: ['', '', '', '', None]
INFO:root:Sample timestamps: ['1723086598', '1723090671', '1723090893', '1723092429', '1723093143']
/home/fedqrbtb/wtsdealnow.com/whatsappsms/sms/smsapp/views.py:1391: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  counts = [int(df['message_body'].str.lower().str.contains(button.lower()).fillna(False).sum()) for button in button_names]
INFO:root:Final query: SELECT * FROM webhook_responses
INFO:root:Final parameters: []
INFO:root:Number of rows fetched: 70523
INFO:root:Sample messages in the data:
INFO:root:Sample messages: ['', '', '', '', None]
INFO:root:Sample timestamps: ['1723086598', '1723090671', '1723090893', '1723092429', '1723093143']
INFO:root:Final query: SELECT * FROM webhook_responses
INFO:root:Final parameters: []
INFO:root:Number of rows fetched: 70523
INFO:root:Sample messages in the data:
INFO:root:Sample messages: ['', '', '', '', None]
INFO:root:Sample timestamps: ['1723086598', '1723090671', '1723090893', '1723092429', '1723093143']
INFO:root:user_response mantej
INFO:root:Error: cannot access local variable 'reply_text' where it is not associated with a value
INFO:root:Error: 'NoneType' object has no attribute 'message_type'
INFO:root:filter_message_response None
INFO:root:user_response mantej
INFO:root:Error: cannot access local variable 'reply_text' where it is not associated with a value
INFO:root:Error: 'NoneType' object has no attribute 'message_type'
INFO:root:filter_message_response None
INFO:root:user_response mantej
INFO:root:Error: cannot access local variable 'reply_text' where it is not associated with a value
INFO:root:message_type: single_product_message
INFO:root:filter_message_response single_product_message - mantej
INFO:root:fastapi https://sendsms-fastapi.onrender.com/bot_api/ {'accept': 'application/json', 'Content-Type': 'application/json'} {'token': 'EAAGnWBuof2oBO0hd9BFZBBEUKLoMZAH1m1JtbUOEd3ZC8GIGjZAyeZB0yFy7SkaByNMKxLQHp6lnstogZAFbJs3b391VCh8uhoxixehHt3vbBYfFuuxvDkjLJEmll48gqw7k33ZCjQxCxgOLK6NpPrtVyTDqSitaPQZBD4dui8EGXajlS1VO35sBOfltsZBvZCMt0mK0u2aQzocFupoPohaIAsz3ZB5fAHoJh6Tm9R9DxKk', 'phone_number_id': '344709618736355', 'contact_list': ['919711618080'], 'message_type': 'single_product_message', 'body': 'Please select product', 'product_data': {'product_retailer_id': '92823252965'}, 'catalog_id': '74765363'}
INFO:root:<class 'list'>
INFO:root:user_response service2
INFO:root:Error: cannot access local variable 'reply_text' where it is not associated with a value
INFO:root:Error: 'NoneType' object has no attribute 'message_type'
INFO:root:filter_message_response None
INFO:root:user_response servic2
INFO:root:Error: cannot access local variable 'reply_text' where it is not associated with a value
INFO:root:message_type: send_text_message
INFO:root:filter_message_response send_text_message - servic2
INFO:root:fastapi https://sendsms-fastapi.onrender.com/bot_api/ {'accept': 'application/json', 'Content-Type': 'application/json'} {'token': 'EAAGnWBuof2oBO0hd9BFZBBEUKLoMZAH1m1JtbUOEd3ZC8GIGjZAyeZB0yFy7SkaByNMKxLQHp6lnstogZAFbJs3b391VCh8uhoxixehHt3vbBYfFuuxvDkjLJEmll48gqw7k33ZCjQxCxgOLK6NpPrtVyTDqSitaPQZBD4dui8EGXajlS1VO35sBOfltsZBvZCMt0mK0u2aQzocFupoPohaIAsz3ZB5fAHoJh6Tm9R9DxKk', 'phone_number_id': '344709618736355', 'contact_list': ['919711618080'], 'message_type': 'text', 'body': 'service '}
INFO:root:<class 'list'>
INFO:smsapp.views:User Opendir logged in successfully.
INFO:root:Final query: SELECT * FROM webhook_responses
INFO:root:Final parameters: []
INFO:root:Number of rows fetched: 70531
INFO:root:Sample messages in the data:
INFO:root:Sample messages: ['', '', '', '', None]
INFO:root:Sample timestamps: ['1723086598', '1723090671', '1723090893', '1723092429', '1723093143']
INFO:root:Final query: SELECT * FROM webhook_responses
INFO:root:Final parameters: []
INFO:root:Number of rows fetched: 70531
INFO:root:Sample messages in the data:
INFO:root:Sample messages: ['', '', '', '', None]
INFO:root:Sample timestamps: ['1723086598', '1723090671', '1723090893', '1723092429', '1723093143']
INFO:root:Final query: SELECT * FROM webhook_responses
INFO:root:Final parameters: []
INFO:root:Number of rows fetched: 70531
INFO:root:Sample messages in the data:
INFO:root:Sample messages: ['', '', '', '', None]
INFO:root:Sample timestamps: ['1723086598', '1723090671', '1723090893', '1723092429', '1723093143']
INFO:root:Final query: SELECT * FROM webhook_responses
INFO:root:Final parameters: []
INFO:root:Number of rows fetched: 70531
INFO:root:Sample messages in the data:
INFO:root:Sample messages: ['', '', '', '', None]
INFO:root:Sample timestamps: ['1723086598', '1723090671', '1723090893', '1723092429', '1723093143']
INFO:root:Final query: SELECT * FROM webhook_responses
INFO:root:Final parameters: []
INFO:root:Number of rows fetched: 70531
INFO:root:Sample messages in the data:
INFO:root:Sample messages: ['', '', '', '', None]
INFO:root:Sample timestamps: ['1723086598', '1723090671', '1723090893', '1723092429', '1723093143']
/home/fedqrbtb/wtsdealnow.com/whatsappsms/sms/smsapp/views.py:1391: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  counts = [int(df['message_body'].str.lower().str.contains(button.lower()).fillna(False).sum()) for button in button_names]
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: opinder@gmail.com, campaign title: test_mantej_sir
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 2
INFO:smsapp.functions.send_messages:Coins deducted: 2. Remaining balance: 1636
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: test_mantej_sir, user: opinder@gmail.com
INFO:root:Error: cannot access local variable 'user_response' where it is not associated with a value
INFO:root:filter_message_response None
INFO:root:image_id 
INFO:root:Error image_id format is incorrect. Expected format: 'id|type'
INFO:root:Next reply message sent successfully. Template: opender001, Phone Number: 919711618080, Media Type: <class 'str'>, Image ID Type: <class 'NoneType'>
INFO:root:Error: cannot access local variable 'user_response' where it is not associated with a value
INFO:root:filter_message_response None
INFO:root:image_id 
INFO:root:Error image_id format is incorrect. Expected format: 'id|type'
INFO:root:Next reply message sent successfully. Template: realesatecontentyh, Phone Number: 919711618080, Media Type: <class 'str'>, Image ID Type: <class 'NoneType'>
INFO:root:Final query: SELECT * FROM webhook_responses
INFO:root:Final parameters: []
INFO:root:Number of rows fetched: 70541
INFO:root:Sample messages in the data:
INFO:root:Sample messages: ['', '', '', '', None]
INFO:root:Sample timestamps: ['1723086598', '1723090671', '1723090893', '1723092429', '1723093143']
/home/fedqrbtb/wtsdealnow.com/whatsappsms/sms/smsapp/views.py:1391: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  counts = [int(df['message_body'].str.lower().str.contains(button.lower()).fillna(False).sum()) for button in button_names]
Request successful!
389460670923677 view flow en MARKETING EAAGnWBuof2oBO0hd9BFZBBEUKLoMZAH1m1JtbUOEd3ZC8GIGjZAyeZB0yFy7SkaByNMKxLQHp6lnstogZAFbJs3b391VCh8uhoxixehHt3vbBYfFuuxvDkjLJEmll48gqw7k33ZCjQxCxgOLK6NpPrtVyTDqSitaPQZBD4dui8EGXajlS1VO35sBOfltsZBvZCMt0mK0u2aQzocFupoPohaIAsz3ZB5fAHoJh6Tm9R9DxKk flow_testing02 1499708400746445
{'id': '526359070302517', 'status': 'REJECTED', 'category': 'MARKETING'}
Response Content: {"id":"526359070302517","status":"REJECTED","category":"MARKETING"}
Response Status Code: 200
389460670923677 view flow en UTILITY EAAGnWBuof2oBO0hd9BFZBBEUKLoMZAH1m1JtbUOEd3ZC8GIGjZAyeZB0yFy7SkaByNMKxLQHp6lnstogZAFbJs3b391VCh8uhoxixehHt3vbBYfFuuxvDkjLJEmll48gqw7k33ZCjQxCxgOLK6NpPrtVyTDqSitaPQZBD4dui8EGXajlS1VO35sBOfltsZBvZCMt0mK0u2aQzocFupoPohaIAsz3ZB5fAHoJh6Tm9R9DxKk flow_testing02 1499708400746445
400 Client Error: Bad Request for url: https://graph.facebook.com/v20.0/389460670923677/message_templates
response <Response [400]>
IDs None None None
Run time of job "schedule_messages (trigger: interval[0:45:00], next run at: 2024-11-15 15:43:25 IST)" was missed by 0:17:30.259246
INFO:smsapp.views:User opinder@gmail.com logged in successfully.
INFO:root:Final query: SELECT * FROM webhook_responses
INFO:root:Final parameters: []
INFO:root:Number of rows fetched: 70542
INFO:root:Sample messages in the data:
INFO:root:Sample messages: ['', '', '', '', None]
INFO:root:Sample timestamps: ['1723086598', '1723090671', '1723090893', '1723092429', '1723093143']
/home/fedqrbtb/wtsdealnow.com/whatsappsms/sms/smsapp/views.py:1391: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  counts = [int(df['message_body'].str.lower().str.contains(button.lower()).fillna(False).sum()) for button in button_names]
INFO:root:Final query: SELECT * FROM webhook_responses
INFO:root:Final parameters: []
INFO:root:Number of rows fetched: 70542
INFO:root:Sample messages in the data:
INFO:root:Sample messages: ['', '', '', '', None]
INFO:root:Sample timestamps: ['1723086598', '1723090671', '1723090893', '1723092429', '1723093143']
INFO:root:Final query: SELECT * FROM webhook_responses
INFO:root:Final parameters: []
INFO:root:Number of rows fetched: 70542
INFO:root:Sample messages in the data:
INFO:root:Sample messages: ['', '', '', '', None]
INFO:root:Sample timestamps: ['1723086598', '1723090671', '1723090893', '1723092429', '1723093143']
INFO:root:Final query: SELECT * FROM webhook_responses
INFO:root:Final parameters: []
INFO:root:Number of rows fetched: 70542
INFO:root:Sample messages in the data:
INFO:root:Sample messages: ['', '', '', '', None]
INFO:root:Sample timestamps: ['1723086598', '1723090671', '1723090893', '1723092429', '1723093143']
INFO:smsapp.views:User varun1@gmail.com logged in successfully.
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: varun1@gmail.com, campaign title: test
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 1
INFO:smsapp.functions.send_messages:Coins deducted: 1. Remaining balance: 3957
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: varun1@gmail.com, campaign title: test
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 1
INFO:smsapp.functions.send_messages:Coins deducted: 1. Remaining balance: 3956
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: test, user: varun1@gmail.com
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: test, user: varun1@gmail.com
INFO:root:Error: cannot access local variable 'user_response' where it is not associated with a value
INFO:root:filter_message_response None
INFO:root:image_id 
INFO:root:Error image_id format is incorrect. Expected format: 'id|type'
INFO:root:Next reply message sent successfully. Template: singlecointesst, Phone Number: 919711340505, Media Type: <class 'str'>, Image ID Type: <class 'NoneType'>
INFO:root:Error: cannot access local variable 'user_response' where it is not associated with a value
INFO:root:filter_message_response None
INFO:root:image_id 
INFO:root:Error image_id format is incorrect. Expected format: 'id|type'
INFO:root:Next reply message sent successfully. Template: singlecoineretrt, Phone Number: 919711340505, Media Type: <class 'str'>, Image ID Type: <class 'NoneType'>
IDs None None None
IDs None None None
IDs None None None
IDs None None None
IDs None None None
IDs None None None
INFO:smsapp.views:User shahzadalam769@gmail.com logged in successfully.
INFO:root:user_response Hi
INFO:root:Error: cannot access local variable 'reply_text' where it is not associated with a value
INFO:root:Error: 'NoneType' object has no attribute 'message_type'
INFO:root:filter_message_response None
INFO:root:user_response Greetings from IT SOLUTION 4 INDIA \U0001f91d

IT SOLUTION 4 INDIA is a one of the best IT Advertising Company in pan india , 

we provide various type of services in all-over pan India such as \U0001f447\U0001f3af

1. \U0001f4acBulk SMS
2. \U0001f4ddLead Generation 
3. \U0001f469\u200d\U0001f4bbDigital Marketing 
4. \U0001f4deVoice calls
5. \u260e\ufe0fIVR Service
6. \U0001f4ddWebsite Development
7. \U0001f516E-commerce Management 
8. \U0001f52dGraphic Designing 
9. \U0001f4f1Election Campaign Management

For More Information\U0001f447
Itsolution4india.com

\U0001f4de 91-9711347474
INFO:root:Error: cannot access local variable 'reply_text' where it is not associated with a value
INFO:root:Error: 'NoneType' object has no attribute 'message_type'
INFO:root:filter_message_response None
[UID:1024][71262] Child process with pid: 97345 was killed by signal: 15, core dumped: no
[UID:1024][71262] Child process with pid: 97367 was killed by signal: 15, core dumped: no
[UID:1024][71262] Child process with pid: 97383 was killed by signal: 15, core dumped: no
[UID:1024][71262] Child process with pid: 97406 was killed by signal: 15, core dumped: no
[UID:1024][71262] Child process with pid: 97424 was killed by signal: 15, core dumped: no
[UID:1024][71262] Child process with pid: 97444 was killed by signal: 15, core dumped: no
[UID:1024][71262] Child process with pid: 97462 was killed by signal: 15, core dumped: no
[UID:1024][71262] Child process with pid: 97483 was killed by signal: 15, core dumped: no
[UID:1024][71262] Child process with pid: 97504 was killed by signal: 15, core dumped: no
[UID:1024][71262] Child process with pid: 97530 was killed by signal: 15, core dumped: no
[UID:1024][71262] Child process with pid: 97583 was killed by signal: 15, core dumped: no
[UID:1024][71262] Child process with pid: 97612 was killed by signal: 15, core dumped: no
[UID:1024][71262] Child process with pid: 97632 was killed by signal: 15, core dumped: no
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: rahul.yadav@bhaaratwealthgroup.com, campaign title: night
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 0
INFO:smsapp.functions.send_messages:Coins deducted: 0. Remaining balance: 9430
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: night, user: rahul.yadav@bhaaratwealthgroup.com
INFO:root:discount 98
INFO:root:discountnumber 337
INFO:smsapp.functions.send_messages:Sending messages for user: rahul.yadav@bhaaratwealthgroup.com, campaign title: night
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 344
INFO:smsapp.functions.send_messages:Coins deducted: 344. Remaining balance: 9086
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: night, user: rahul.yadav@bhaaratwealthgroup.com
IDs None None None
4::dmlkZW8vbXA0:ARabOFexwtElRrBbtzfyp4jrYzKqoBIlD1-O8yc5iCMP5Qcr7t5cxEHljfttNNSD-6EmwMD46BbpryaOaoeSEncMHDXQClJju_8RvCIECMAgrw:e:1732036674:465471839698794:61565150340230:ARbIFUAOMFlS-A-DstU
4::dmlkZW8vbXA0:ARaknC5tA_64uQ9cKF6R8l3T9gd7z9bXLjK0FsAKWpjrkZdm2yeAhbD6iRtzFjajOXRBPhVF9eAr9nztUUYswr9h98ueMDjTngUiVODlruhXUg:e:1732036674:465471839698794:61565150340230:ARZ5LlaXENSQWh8484s
[UID:1024][1394484] Child process with pid: 1394500 was killed by signal: 15, core dumped: no
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
INFO:smsapp.views:User varun1@gmail.com logged in successfully.
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: varun1@gmail.com, campaign title: test
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 0
INFO:smsapp.functions.send_messages:Coins deducted: 0. Remaining balance: 3956
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: test, user: varun1@gmail.com
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: varun1@gmail.com, campaign title: test
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 0
INFO:smsapp.functions.send_messages:Coins deducted: 0. Remaining balance: 3956
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: test, user: varun1@gmail.com
INFO:root:discount 0
INFO:root:discountnumber 0
INFO:smsapp.functions.send_messages:Sending messages for user: varun1@gmail.com, campaign title: test
INFO:smsapp.functions.send_messages:Calculated money data for sending messages: 0
INFO:smsapp.functions.send_messages:Coins deducted: 0. Remaining balance: 3956
INFO:smsapp.functions.send_messages:Messages sent successfully for campaign: test, user: varun1@gmail.com
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/fedqrbtb/virtualenv/wtsdealnow.com/whatsappsms/sms/3.12/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wtsdealnow.in'. You may need to add 'wtsdealnow.in' to ALLOWED_HOSTS.
INFO:smsapp.views:User rahul.yadav@bhaaratwealthgroup.com logged in successfully.
INFO:smsapp.views:User opinder@gmail.com logged in successfully.
